files = shader.cpp

CXX = g++
CXXFLAGS = -std=c++11 -g -Wall

LIBS = -lglfw -lGLEW -lGL -ldl -lpthread

main: main.cpp $(files)
	$(CXX) $(CXXFLAGS) main.cpp $(files) $(LIBS) -o main

run: main
	./main

clean:
	rm -f *.o main

all:
	$(MAKE) clean
	$(MAKE)
	$(MAKE) run